workspace = { members = ["examples/mnist"] }
[package]
name = "matrix-nn"
version = "1.0.0"
edition = "2021"

[dependencies]
num_cpus = "1.16"
rand = "0.9.0-alpha"
anyhow = "1"
# log = "0.4.21"
# env_logger = "0.11"
bincode = "2.0.0-rc"
